### ISSUE TITLE
ORCID new config

### ISSUE THREAD

**Issue by g-sam** [elifesciences/elife-xpub-formula#18]
Future deploys will require a new config item for orcid oauth: see https://gitlab.coko.foundation/yld/xpub-deployment-config-postgres/commit/6b4e54858262cfad43fa00dced39f1b1a8ee872b

We are using a sandbox account there. you may wish to use your own account.

**Comment by giorgiosironi** [comment]
To use the real one, we should put `sandbox` to `false`?

**Comment by g-sam** [comment]
yes, or delete the key

**Comment by giorgiosironi** [comment]
Closing, implemented in https://github.com/elifesciences/elife-xpub-formula/blob/master/salt/elife-xpub/init.sls#L26-L27
